CHAINS:
  - name: "Ethereum"
    tag: "ETH"
    scan:
      api: "https://api-cn.etherscan.com/api"
      keys:
        - "7MM6JYY49WZBXSYFDPYQ3V7V3EMZWE4KJK"
    nodes:
      - api: "https://eth-mainnet.alchemyapi.io/v2/AgKT8OzbNsYnul856tenwnsnL3Pm7WRB"

  - name: "Binance Smart Chain"
    tag: "BSC"
    scan:
      api: "https://api.bscscan.com/api"
      keys:
        - "S7N1S396ZB98XYC5WQ3IWEPDBGJKESXH5B"
        - "EGAQYID9BS2H4YC3WJITVZTXDHYSWIUJDS"
    nodes:
      - api: "https://bsc-dataseed1.ninicoin.io/"
      - api: "https://bsc-dataseed2.ninicoin.io/"
      - api: "https://bsc-dataseed3.ninicoin.io/"
      - api: "https://bsc-dataseed4.ninicoin.io/"
      - api: "https://bsc-dataseed1.defibit.io/"
      - api: "https://bsc-dataseed2.defibit.io/"
      - api: "https://bsc-dataseed3.defibit.io/"
      - api: "https://bsc-dataseed4.defibit.io/"

  - name: "Polygon"
    tag: "POL"
    scan:
      api: "https://api.polygonscan.com/api"
      keys:
        - "7BTFI86WFGAAD91X2AGSF7YWBWC3M4R39S"
    nodes:
      - api: "https://polygon-rpc.com"
      - api: "https://rpc-mainnet.maticvigil.com"

